color: null
fieldLayouts:
  4085fada-a311-4aa1-9090-292dd3439322:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-28T16:29:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 902aec6a-9d6d-4d7a-a42d-3c35e5d9729e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-28T16:30:38+00:00'
            elementCondition: null
            fieldUid: f021cc07-c4ac-4c37-8098-04da97610f55 # Asset
            handle: categoryImage
            includeInCards: false
            instructions: null
            label: 'Category Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcee53a3-b0de-4b81-bad9-1619c8e018ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1a76b62-6a5d-48a6-994e-0e8bdca09254
        userCondition: null
handle: category
hasTitleField: true
icon: null
name: Category
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
