color: null
fieldLayouts:
  74f7c4e4-89da-46f3-856b-32fe9771bb0d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6bdc15e4-e20a-49a3-9441-a0543cbbef8d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb389677-b707-4127-b1e0-e72b8a5d14d0
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66de862a-1dd2-4a37-8e35-aed3594eb9a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a8abdcb-66fe-4faa-a3af-6b7906df6a27
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ee76c1-a95d-4b54-a386-a119bfd3ffb1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52c379ed-720e-4e54-93da-921bc816881f
        userCondition: null
handle: contentRow
hasTitleField: false
icon: ''
name: 'Content Row'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Content Row'
titleTranslationKeyFormat: null
titleTranslationMethod: site
