color: null
fieldLayouts:
  f4646077-7c14-4c50-ac50-89d909222851:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf6ae521-cf00-4343-ba17-8b1fc6234417
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2c2fe3d-88a8-4e22-b922-d8b092cd5c8c # Plain Text
            handle: itemHeading
            includeInCards: false
            instructions: null
            label: 'Item Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6562a004-37ea-4f06-bddf-7481da845d94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29c74bc0-63b8-4a8e-af6e-5b532f61cf89 # Rich Text
            handle: itemContent
            includeInCards: false
            instructions: null
            label: 'Item Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a184927d-bfb4-4bf8-bd15-fcba3fd0443d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15fb37f6-63d7-4ae6-adb2-8f766384d9be
        userCondition: null
handle: tabContentItem
hasTitleField: false
icon: ''
name: 'Tab Content Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Tab Content Item'
titleTranslationKeyFormat: null
titleTranslationMethod: site
