altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  336fb43e-48f6-4c42-8b84-5dc83efa946c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 03e77a36-d0e2-44ec-8293-9369d0b88887
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 141db216-d252-4143-97a6-5fc6d0d8717a
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
