columnSuffix: null
handle: categories
instructions: null
name: Categories
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add Category'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:0089651a-3029-4ac7-80c7-e2219acba8df' # Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
