columnSuffix: null
handle: newsTags
instructions: null
name: 'News Tags'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add News Tag'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:dad78aff-52ed-4b07-ace2-764077487400' # News Tags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
