columnSuffix: null
handle: showChildren
instructions: null
name: 'Show Children'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
