columnSuffix: null
handle: showInSitemap
instructions: null
name: 'Show in Sitemap'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
