columnSuffix: null
handle: sitemapPriority
instructions: null
name: 'Sitemap Priority'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '0.5 (Listing)'
        -
          - value
          - '0.5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '0.8 (Normal Page)'
        -
          - value
          - '0.8'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '1 (Homepage)'
        -
          - value
          - '1.0'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
