defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 745f7d5f-5313-4479-b303-6fb9e1e72116 # Page
handle: information
maxAuthors: 1
name: Information
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  849a5a43-c78b-450f-866f-19cf4b92b6a2: # Technical Test
    enabledByDefault: true
    hasUrls: true
    template: _pages/_index.twig
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
type: channel
